"""
generate_checksums.py — Data integrity verification
=====================================================
Generates SHA-256 hashes for all data files used in the analysis.
Run once after downloading Odlyzko zero files, then commit
CHECKSUMS.sha256 to the repository.

Usage:
  python scripts/generate_checksums.py

Output:
  data_v1/CHECKSUMS.sha256
"""

import hashlib
import os
import sys
from pathlib import Path

FILES_TO_HASH = [
    "zeros2.txt",
    "zeros3.txt",
    "zeros4.txt",
    "data_v1/primes/primes_v1.txt",
]

def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

def main():
    root = Path(__file__).parent.parent
    out  = root / "data_v1" / "CHECKSUMS.sha256"

    lines = [
        "# SHA-256 checksums — generated by scripts/generate_checksums.py",
        "# Verify with: sha256sum --check data_v1/CHECKSUMS.sha256",
        f"# Generated: {__import__('datetime').date.today()}",
        "",
    ]

    found = []
    missing = []

    for rel in FILES_TO_HASH:
        path = root / rel
        if path.exists():
            digest = sha256(path)
            lines.append(f"{digest}  {rel}")
            found.append(rel)
            print(f"  ✓  {rel}")
            print(f"     {digest}")
        else:
            lines.append(f"# MISSING: {rel}")
            missing.append(rel)
            print(f"  ✗  {rel} (not found — download from Odlyzko)")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")

    print(f"\nWritten: {out}")
    print(f"Found: {len(found)}/{len(FILES_TO_HASH)} files")

    if missing:
        print(f"\nMissing files ({len(missing)}):")
        for f in missing:
            print(f"  {f}")
        print("\nDownload zeros from:")
        print("  http://www-users.cse.umn.edu/~odlyzko/zeta_tables/")

if __name__ == "__main__":
    main()
